'use client';

import {
  Home,
  User,
  Zap,
  Briefcase,
  Layers,
  Award,
  Github,
  Linkedin,
  Mail,
  Activity,
  Cpu,
  Shield,
  Cloud,
  Boxes,
  GitBranch,
  FileCode,
  Terminal,
  LayoutDashboard,
  Sparkles,
  BarChart3,
  Trophy,
  Moon,
  Sun,
  MonitorSmartphone,
  ArrowRight,
  ArrowUpRight,
  ArrowDown,
  ArrowUp,
  Minus,
  Eye,
  MapPin,
  Phone,
  ChevronDown,
  Copy,
  Check,
  CircleDot,
  X,
  GraduationCap,
  Heart,
  type LucideIcon,
} from 'lucide-react';

const registry: Record<string, LucideIcon> = {
  home: Home,
  user: User,
  zap: Zap,
  briefcase: Briefcase,
  layers: Layers,
  award: Award,
  github: Github,
  linkedin: Linkedin,
  mail: Mail,
  activity: Activity,
  cpu: Cpu,
  shield: Shield,
  cloud: Cloud,
  boxes: Boxes,
  'git-branch': GitBranch,
  'file-code': FileCode,
  terminal: Terminal,
  'layout-dashboard': LayoutDashboard,
  sparkles: Sparkles,
  'bar-chart-3': BarChart3,
  trophy: Trophy,
  moon: Moon,
  sun: Sun,
  system: MonitorSmartphone,
  arrow: ArrowRight,
  'arrow-up-right': ArrowUpRight,
  up: ArrowUp,
  down: ArrowDown,
  flat: Minus,
  eye: Eye,
  'map-pin': MapPin,
  phone: Phone,
  chevron: ChevronDown,
  copy: Copy,
  check: Check,
  dot: CircleDot,
  x: X,
  'arrow-right': ArrowRight,
  'graduation-cap': GraduationCap,
  heart: Heart,
};

export function Icon({
  name,
  className,
  size = 18,
  strokeWidth = 1.8,
}: {
  name: string;
  className?: string;
  size?: number;
  strokeWidth?: number;
}) {
  const C = registry[name] ?? Sparkles;
  return <C className={className} size={size} strokeWidth={strokeWidth} aria-hidden />;
}
